### PR TITLE
Fix: #334. Add .yamlld and .jsonld extensions.

### PR DESCRIPTION
**Pull request by ioggstream**
## This PR

- adds .yamlld and .jsonld extensions

### CODE REVIEW

**Comment by asottile** [comment]
these should probably be classified as both their `ld` equivalents and the base config language as well in case one would want to lint those specifically

**Comment by ioggstream** [comment]
Hi @asottile! I landed here from pre-commit.

1. The desiderata is that jsonld and yamlld are at least linted with the JSON/yaml linters. It seems that check-yaml skips .yamlld files 

2. It is possible to add further validation (eh using jsonld) JSON schema but it is a complex task to be achieved consistently.

How do you think it is possible to achieve point 1?

Have a nice day!

**Comment by asottile** [comment]
your patch does part 1 but you need to address my comment to get merged

**Comment by ioggstream** [comment]
PTAL I "copied" from the xhtml entry. Have a nice day, R.

**Review by asottile — APPROVED** [review]

**Pull request merged**
