### PR TITLE
Add DDL file extension as Text/SQL

### PR DESCRIPTION
**Pull request by 1337Lurker**
### Changes
---
- [x] Add `ddl` extension support as Text/SQL file extension.

### CODE REVIEW

**Comment by asottile** [comment]
do you have a reference for this?  I scrolled through 10 pages of github searches for `*.ddl` and didn't find any ddl files which were sql (one was a proprietary format, the other was vbscript)

**Comment by 1337Lurker** [comment]
It's one of Jetbrains' DataGrip default file extensions, pictured [here](https://www.jetbrains.com/help/datagrip/creating-and-registering-file-types.html#change-extension) (second image down):

From my local IDE:

image

From my own experience, `sql` and `ddl` are used, but I'm not familiar with `cql`, and, as such` did not add it.

**Comment by asottile** [comment]
unless you can come up with an official documented resource and some examples I can't accept this

**Comment by 1337Lurker** [comment]
Upon further review, it looks like `ddl` is only a local convention, and the larger convention is to only use `sql` and not differentiate between DCL/DDL/DML/DQL using file extensions.

Thanks for all the quick responses, @asottile, I am much obliged, sir.

**Pull request closed without merging**
