### PR TITLE
Identify config.ru rackup file as ruby

### PR DESCRIPTION
**Pull request by mmlb**

### CODE REVIEW

**Comment by asottile** [comment]
can you provide a reference?  I'm having a bit of a difficult time finding what uses this

**Comment by mmlb** [comment]
Hey @asottile here you go https://github.com/rack/rack#usage. I'm not super into the ruby web community but do work on a rack/rails app (I guess...?) a little bit for work. I'm not sure if it makes sense to limit to config.ru (GH search shows a few files that look like ruby that aren't explicitly named config.ru), GH's linguist just goes off of the extension .ru: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L5968

Would it be better to to just go with the extension?

**Review by asottile — APPROVED** [review]

**Comment by mmlb** [comment]
:tada:

**Pull request merged**
